### ISSUE TITLE
The app stopped working 

### ISSUE THREAD

**Issue by rianaokel** [BeamlakAschalew/cinemax#43]
### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

.

### Android version

12

### Other details

You can't play the movies or tv shows at all. How can i host the app on my website ?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by BeamlakAschalew** [comment]
Sorry for the late reply. The app stopped working because of a problem with [Consumet](https://github.com/consumet) but I am trying to find alternatives. 
And what is your website and how are you planning to host it?

**Comment by DarkCrypt** [comment]
@BeamlakAschalew 
I was hoping Consumet was going to be awesome but not if it continues to have issues. I've read others suggesting to self host it instead of running off of their instance. I think they also have rate limits in place with their instance. Maybe you're already self hosting?

I'm also still continuously looking for more api sources but keep coming up short. All I can seem to find is sources for torrents but that's not what I'm looking for. Maybe you're going to have to go back to scraping instead?

**Comment by BeamlakAschalew** [comment]
Are you rererring to the Self hosting as in hosting the script using Vercel? If so, I was already doing that, it's the "watch" endpoint that stopped working. But can you send me the forum you saw this discussion?

And scraping is hard and not free and I have to bypass captcha's every time it's not worth it. Plus many of the sites use Consumet so it's pointless.

**Comment by DarkCrypt** [comment]
Yeah, the suggested self hosting is by using Vercel or one of the other methods mentioned in Consumet's README. But you're already doing that like you said. If I looked at your code better I would've seen that, my bad. I was looking through Consumet's issues when I read the suggestion, all four issues were posted for FlixHQ: [#310](https://github.com/consumet/api.consumet.org/issues/310), [#375](https://github.com/consumet/api.consumet.org/issues/375), [#417](https://github.com/consumet/api.consumet.org/issues/417), and [#443](https://github.com/consumet/api.consumet.org/issues/443).

I understand your reasons to not want to scrape but I don't know what the expenses are financially. I know this isn't fail safe but could you use CloudStream's extensions?

I did find more api's but they all seem to be embeds. So far all I've been able to find is Consumet, torrent sources, embed apis, file hosts, and CloudStream extensions. Basically the usual stuff, not sure what else there is. The only other thing I can think of at this time is creating your own api?

**Comment by riimuru** [comment]
@BeamlakAschalew This problem was resolved 4 days ago [on Consumet](https://github.com/consumet/consumet.ts/pull/369). On your hosted instance, be sure to delete your .lock files and reinstall packages. Alternatively, you can write a script (using GitHub actions or Docker) to automatically update and deploy your hosted instance whenever there are updates. Flixhq recently went down due to them changing their ani-scrape technique. And there will never be a permanent solution to this problem. If you don't want to deal with that issue anymore, I recommend you start hosting your own source files ***(really risky)***.

**Comment by BeamlakAschalew** [comment]
> @BeamlakAschalew This problem was resolved 4 days ago [on Consumet](https://github.com/consumet/consumet.ts/pull/369). On your hosted instance, be sure to delete your .lock files and reinstall packages. Alternatively, you can write a script (using GitHub actions or Docker) to automatically update and deploy your hosted instance whenever there are updates. Flixhq recently went down due to them changing their ani-scrape technique. And there will never be a permanent solution to this problem. If you don't want to deal with that issue anymore, I recommend you start hosting your own source files _**(really risky)**_.

Thank you for notifying!

**Comment by BeamlakAschalew** [comment]
> @BeamlakAschalew This problem was resolved 4 days ago [on Consumet](https://github.com/consumet/consumet.ts/pull/369). On your hosted instance, be sure to delete your .lock files and reinstall packages. Alternatively, you can write a script (using GitHub actions or Docker) to automatically update and deploy your hosted instance whenever there are updates. Flixhq recently went down due to them changing their ani-scrape technique. And there will never be a permanent solution to this problem. If you don't want to deal with that issue anymore, I recommend you start hosting your own source files _**(really risky)**_.

Deleted and rehosted https://github.com/consumet/api.consumet.org on Vercel but the watch endpoint is still not working
